### ISSUE TITLE
Sprint 2: Frontend Base and Authentication

### ISSUE THREAD

**Issue by vladar21** [vladar21/pimp-my-english#8]
**Duration:** 4 days (May 25, 2024 - May 28, 2024)

**Goals:**
- Develop the basic frontend structure.
- Implement user authentication and authorization.

**User Stories:**
- As a Subscriber, I want to log into the site to access my subscriptions settings and word sets.
- As an Admin, I want to manage the entire platform to ensure smooth operations and content quality.

**Tasks:**
- [x] Create Base Templates (May 25, 2024)
  - **Description:** Add templates base, landing, register.
    - **Commit:** 25ed94eb06bf9dad0b7762d6fef55d5edb5618df
- [x] Set Up Frontend Base (May 25, 2024)
  - **Description:** Add frontend base and landing pages.
    - **Commit:** d217c1b32b26403c95761c4dff1bc838cb7a13d0
- [x] User Authentication (May 26, 2024)
  - **Description:** Make migrations.
    - **Commit:** f3f4749633e310b4050bb82ec206bf5450a0d36c
  - **Description:** Add auth backend.
    - **Commit:** c588bc6509f806257be0e4cf860e0e59fe6fa8ce
- [x] User Authorization (May 27, 2024)
  - **Description:** Add users app for user and auth management.
    - **Commit:** baa16c076ac898fddbc932317c3bc76656e62764
- [x] Finalize User Management (May 28, 2024)
  - **Description:** Remove users app.
    - **Commit:** c30f77bca3d2bf2fba219ea4195cd4f74cc1adb9
